name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libncurses5 \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          openjdk-17-jdk \
          unzip \
          git \
          wget \
          libbz2-dev \
          libreadline-dev \
          liblzma-dev \
          libncursesw5-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Setup Android SDK & Accept Licenses
      env:
        ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
      run: |
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        cd "$ANDROID_SDK_ROOT/cmdline-tools"

        # Download and unzip command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip -q tools.zip
        rm tools.zip
        mv cmdline-tools latest

        # Install SDK components
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses

        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

        echo "✅ Android SDK Setup Complete"

    - name: Configure Buildozer spec (API 33 + Build-Tools 33.0.2)
      run: |
        if [ -f buildozer.spec ]; then
          sed -i 's/^# *android.api = .*/android.api = 33/' buildozer.spec
          sed -i 's/^# *android.build_tools = .*/android.build_tools = 33.0.2/' buildozer.spec
        fi

    - name: Init Buildozer (if no spec)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apkozer.spec ]; then
          sed -i 's/^# *android.build_tools = .*/android.build_tools = 33.0.2/' buildozer.spec
          sed -i 's/^# *android.api = .*/android.api = 33/' buildozer.spec
        fi

    - name: Initialize buildozer if missing
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk