name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libncurses5 \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          openjdk-17-jdk \
          unzip \
          git \
          wget \
          libbz2-dev \
          libreadline-dev \
          liblzma-dev \
          libncursesw5-dev

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg

    - name: Configure Build Tools version
      run: |
        if [ -f buildozer.spec ]; then
          sed -i 's/# android.build_tools = .*/android.build_tools = 33.0.2/' buildozer.spec
          sed -i 's/# android.api = .*/android.api = 33/' buildozer.spec
        fi

    - name: Initialize buildozer (if missing)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
