# .github/workflows/buildozer.yml
name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          zip unzip git wget curl \
          openjdk-17-jdk \
          libncurses6 \
          libstdc++6 \
          python3-pip

    - name: Install buildozer
      run: |
        pip install --upgrade pip
        pip install cython virtualenv
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-apk
        path: bin/*.apk
