name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libncurses5 \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          openjdk-17-jdk \
          unzip \
          git \
          wget \
          libbz2-dev \
          libreadline-dev \
          liblzma-dev \
          libncursesw5-dev

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Setup Android SDK and accept licenses
      env:
        ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
      run: |
        mkdir -p "$ANDROID_SDK_ROOT"

        # Install cmdline-tools
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        rm cmdline-tools.zip
        mv cmdline-tools "$ANDROID_SDK_ROOT/cmdline-tools/latest"

        # Accept licenses
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses

        # Install required tools only
        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

        # Confirm aidl is present
        if [ ! -f "$ANDROID_SDK_ROOT/build-tools/33.0.2/aidl" ]; then
          echo "ERROR: aidl not found!"
          exit 1
        fi

    - name: Configure Buildozer build tools and API
      run: |
        if [ -f buildozer.spec ]; then
          sed -i 's/^# *android.build_tools = .*/android.build_tools = 33.0.2/' buildozer.spec
          sed -i 's/^# *android.api = .*/android.api = 33/' buildozer.spec
        fi

    - name: Initialize buildozer if missing
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk