name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # ✅ Use stable LTS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5 libffi-dev libssl-dev libsqlite3-dev zlib1g-dev openjdk-17-jdk unzip git wget

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Initialize buildozer
      run: |
        buildozer init || true  # skip if already exists

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
