name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          libncurses5 \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          openjdk-17-jdk \
          unzip \
          git \
          wget \
          libbz2-dev \
          libreadline-dev \
          liblzma-dev \
          libncursesw5-dev

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Setup Android SDK and accept licenses
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk

        # Clean old build-tools to avoid conflicts
        rm -rf $ANDROID_SDK_ROOT/build-tools/*

        # Install cmdline-tools if missing
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm cmdline-tools.zip
        fi

        # Accept licenses
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install only the pinned SDK components
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2" "platform-tools"

    - name: Configure Buildozer build tools and API
      run: |
        if [ -f buildozer.spec ]; then
          sed -i 's/^# *android.build_tools = .*/android.build_tools = 33.0.2/' buildozer.spec
          sed -i 's/^# *android.api = .*/android.api = 33/' buildozer.spec
        fi

    - name: Initialize buildozer if missing
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk